### PR TITLE
Theme context menu (fix #1)

### LINKED ISSUE #1: Context menu is not themed on macOS
**Issue**:  
On macOS, the context menu (right click) is not themed.
Unthemed context menu
Unthemed toolbar context menu

**Operating System**: macOS 10.14.6
**Browser Version**: 68.0.1 (64-bit)

### PR DESCRIPTION
**Pull request by vkhitrin**
This pull request fixes #1.

New look:
Themed context menu

### CODE REVIEW

**Comment by vkhitrin** [comment]
@EliverLara,
Not sure how it interacts with GTK, could you please let me know if it breaks something?

---

This commit does not fix an issue where extensions populate context menu, and may result in similar a menu:
Extension context menu item
A fix for this is out of scope for the current commit in my opinion.

**Comment by TwisterMc** [comment]
This works for in page context menus but not if you were to right click on the back/forward buttons

**Comment by vkhitrin** [comment]
@TwisterMc,
Thanks, you are right.

Will sort it out.

**Comment by vkhitrin** [comment]
Consolidating to use `menupopup` to theme most of the context menus which solves some of the extension issues as well.

Please let me know if you experience some issues in some menus (for example, an issue can occur in the screen selection share menu).

**Comment by TwisterMc** [comment]
Looks good! Thanks

**Comment by EliverLara** [comment]
@vkhitrin in gtk it breaks the menu items padding:

Captura de pantalla de 2019-08-02 16-38-43

this is fixable by adding a 4px padding to  items but I don't know how it will look on your side.

**Comment by vkhitrin** [comment]
@EliverLara,
This is how it looks with `padding: 4px` on macOS:
4px padding
I've tried a different padding value `padding: 2px 25px` and it looks good on macOS, could you please try it on GTK?
2px 25px padding

**Comment by EliverLara** [comment]
@vkhitrin with `padding: 2px 25px` the menu looks so big:

Captura de pantalla de 2019-08-03 17-49-49

I think an intermediate point would look good, maybe `padding: 4px 12-16px`?

**Comment by vkhitrin** [comment]
@EliverLara,
`padding: 4px 16px` looks good on my side:
Padding context menu
Added it to the PR.

**Comment by EliverLara** [comment]
@vkhitrin Now looks great on gtk too, thanks!

**Pull request merged**
